/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentScheduleRouteImport } from './routes/studentSchedule'
import { Route as MakeScheduleRouteImport } from './routes/makeSchedule'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthDeniedRouteImport } from './routes/auth.denied'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/studentSchedule',
  path: '/studentSchedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeScheduleRoute = MakeScheduleRouteImport.update({
  id: '/makeSchedule',
  path: '/makeSchedule',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeniedRoute = AuthDeniedRouteImport.update({
  id: '/auth/denied',
  path: '/auth/denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/makeSchedule': typeof MakeScheduleRoute
  '/studentSchedule': typeof StudentScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/makeSchedule': typeof MakeScheduleRoute
  '/studentSchedule': typeof StudentScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/makeSchedule': typeof MakeScheduleRoute
  '/studentSchedule': typeof StudentScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/makeSchedule'
    | '/studentSchedule'
    | '/auth/callback'
    | '/auth/denied'
    | '/auth/login'
    | '/auth/logout'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/makeSchedule'
    | '/studentSchedule'
    | '/auth/callback'
    | '/auth/denied'
    | '/auth/login'
    | '/auth/logout'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/makeSchedule'
    | '/studentSchedule'
    | '/auth/callback'
    | '/auth/denied'
    | '/auth/login'
    | '/auth/logout'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MakeScheduleRoute: typeof MakeScheduleRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthDeniedRoute: typeof AuthDeniedRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studentSchedule': {
      id: '/studentSchedule'
      path: '/studentSchedule'
      fullPath: '/studentSchedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makeSchedule': {
      id: '/makeSchedule'
      path: '/makeSchedule'
      fullPath: '/makeSchedule'
      preLoaderRoute: typeof MakeScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/denied': {
      id: '/auth/denied'
      path: '/auth/denied'
      fullPath: '/auth/denied'
      preLoaderRoute: typeof AuthDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MakeScheduleRoute: MakeScheduleRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthDeniedRoute: AuthDeniedRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
