/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentScheduleRouteImport } from './routes/studentSchedule'
import { Route as MakeScheduleRouteImport } from './routes/makeSchedule'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/studentSchedule',
  path: '/studentSchedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeScheduleRoute = MakeScheduleRouteImport.update({
  id: '/makeSchedule',
  path: '/makeSchedule',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/makeSchedule': typeof MakeScheduleRoute
  '/studentSchedule': typeof StudentScheduleRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/makeSchedule': typeof MakeScheduleRoute
  '/studentSchedule': typeof StudentScheduleRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/makeSchedule': typeof MakeScheduleRoute
  '/studentSchedule': typeof StudentScheduleRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/makeSchedule' | '/studentSchedule' | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/makeSchedule' | '/studentSchedule' | '/api/trpc/$'
  id: '__root__' | '/' | '/makeSchedule' | '/studentSchedule' | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MakeScheduleRoute: typeof MakeScheduleRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studentSchedule': {
      id: '/studentSchedule'
      path: '/studentSchedule'
      fullPath: '/studentSchedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makeSchedule': {
      id: '/makeSchedule'
      path: '/makeSchedule'
      fullPath: '/makeSchedule'
      preLoaderRoute: typeof MakeScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MakeScheduleRoute: MakeScheduleRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
